[package]
name = "world_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
noise = "0.8"
rand = "0.8"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
